
INSERT INTO cms_page_content_2026_06_01 (page,section,field,value_en,value_ar) VALUES
-- HERO
('services','hero','badge','End-to-End Solutions','حلول متكاملة'),
('services','hero','badge_ar','حلول متكاملة','حلول متكاملة'),
('services','hero','heading','Comprehensive','حلول معارض'),
('services','hero','subline','Exhibition Solutions','شاملة ومتكاملة'),
('services','hero','heading_ar','حلول معارض','حلول معارض'),
('services','hero','subline_ar','شاملة ومتكاملة','شاملة ومتكاملة'),
('services','hero','subheading','From concept to completion — we provide end-to-end services that transform your brand vision into powerful, engaging experiences.','من الفكرة للتنفيذ — نقدم خدمات متكاملة تحوّل رؤية براندك إلى تجارب قوية ومؤثرة.'),
('services','hero','subheading_ar','من الفكرة للتنفيذ — نقدم خدمات متكاملة تحوّل رؤية براندك إلى تجارب قوية ومؤثرة.','من الفكرة للتنفيذ — نقدم خدمات متكاملة تحوّل رؤية براندك إلى تجارب قوية ومؤثرة.'),
('services','hero','cta','Get Custom Quote','اطلب عرض سعر'),
-- SERVICE CARD 1
('services','card1','title','Exhibition Booth Design & Build','تصميم وتنفيذ أجنحة المعارض'),
('services','card1','subtitle','Custom-designed booths that captivate and convert','أجنحة مصممة خصيصاً تستقطب الأنظار وتحقق النتائج'),
('services','card1','desc','From concept to completion, we create stunning exhibition booths that tell your brand story and drive meaningful engagement with your target audience.','من الفكرة للتنفيذ، نصمم أجنحة معارض احترافية تعكس هوية براندك وتحقق تفاعلاً حقيقياً مع جمهورك المستهدف.'),
('services','card1','f1','3D Design & Visualization','تصميم ثلاثي الأبعاد وتصور واقعي'),
('services','card1','f2','Custom Branding Integration','دمج هوية البراند بالكامل'),
('services','card1','f3','Interactive Elements','عناصر تفاعلية وتقنية'),
('services','card1','f4','Premium Materials','خامات ممتازة عالية الجودة'),
('services','card1','f5','Modular Systems','أنظمة معيارية قابلة للتوسيع'),
('services','card1','f6','On-site Installation','تركيب ودعم في الموقع'),
('services','card1','p1','Initial Consultation & Brief','استشارة أولية وتحليل المتطلبات'),
('services','card1','p2','3D Design Development','تطوير التصميم ثلاثي الأبعاد'),
('services','card1','p3','Client Approval & Refinement','موافقة العميل والتعديلات'),
('services','card1','p4','Production & Fabrication','التصنيع والإنتاج'),
('services','card1','p5','Installation & Setup','التركيب والإعداد'),
('services','card1','p6','Post-Event Support','الدعم بعد الفعالية'),
-- SERVICE CARD 2
('services','card2','title','Event Production & Management','تنفيذ وإدارة الفعاليات'),
('services','card2','subtitle','Complete event management from concept to execution','إدارة متكاملة للفعاليات من الفكرة حتى التنفيذ'),
('services','card2','desc','Full-service event production including stage design, lighting, audio-visual systems, and on-the-ground management for corporate events and product launches.','خدمة متكاملة في إنتاج الفعاليات تشمل تصميم المسرح والإضاءة وأنظمة الصوت والصورة والإدارة الميدانية للفعاليات المؤسسية.'),
('services','card2','f1','Stage Design & Construction','تصميم وإنشاء المسرح'),
('services','card2','f2','Professional Lighting Systems','أنظمة إضاءة احترافية'),
('services','card2','f3','Audio-Visual Integration','تكامل الصوت والصورة'),
('services','card2','f4','Technical Support Team','فريق دعم تقني متخصص'),
('services','card2','f5','Project Management','إدارة مشروع متكاملة'),
('services','card2','f6','Live Event Coordination','تنسيق الفعالية مباشرة'),
('services','card2','p1','Event Planning & Strategy','تخطيط الفعالية والاستراتيجية'),
('services','card2','p2','Technical Requirements Analysis','تحليل المتطلبات التقنية'),
('services','card2','p3','Design & Setup Planning','التصميم وتخطيط الإعداد'),
('services','card2','p4','Equipment Installation','تركيب المعدات'),
('services','card2','p5','Live Event Management','إدارة الفعالية المباشرة'),
('services','card2','p6','Post-Event Breakdown','التفكيك بعد الفعالية'),
-- SERVICE CARD 3
('services','card3','title','Brand Activations','براند أكتيفيشن'),
('services','card3','subtitle','Immersive experiences that deeply engage audiences','تجارب تفاعلية تترك أثراً حقيقياً في ذاكرة جمهورك'),
('services','card3','desc','Creative brand activations and installations that create memorable interactions between your brand and your audience, driving real engagement and recall.','تفعيلات براند إبداعية ومنشآت تصنع تفاعلاً حقيقياً بين براندك وجمهورك، تُحدث أثراً وتُعزز التذكّر.'),
('services','card3','f1','Concept & Strategy','الفكرة والاستراتيجية'),
('services','card3','f2','Custom Installations','منشآت مخصصة'),
('services','card3','f3','Interactive Experiences','تجارب تفاعلية'),
('services','card3','f4','Brand Storytelling','سرد قصة البراند'),
('services','card3','f5','Audience Engagement','تفاعل الجمهور'),
('services','card3','f6','Post-Activation Reports','تقارير ما بعد التفعيل'),
('services','card3','p1','Brand Analysis & Strategy','تحليل البراند والاستراتيجية'),
('services','card3','p2','Creative Concept Development','تطوير المفهوم الإبداعي'),
('services','card3','p3','Design & Production','التصميم والإنتاج'),
('services','card3','p4','Installation & Testing','التركيب والاختبار'),
('services','card3','p5','Live Activation Management','إدارة التفعيل المباشر'),
('services','card3','p6','Performance Analysis','تحليل الأداء'),
-- SERVICE CARD 4
('services','card4','title','Custom Fabrication','تصنيع مخصص'),
('services','card4','subtitle','Tailored structures for any space and purpose','هياكل مصنوعة وفق مواصفاتك لأي مكان وغرض'),
('services','card4','desc','Modular and custom structures designed to your exact specifications — from temporary installations to permanent displays, kiosks, and architectural elements.','هياكل معيارية ومخصصة مصممة وفق مواصفاتك الدقيقة — من المنشآت المؤقتة إلى العروض الدائمة والكيوسكات والعناصر المعمارية.'),
('services','card4','f1','Modular Design Systems','أنظمة تصميم معيارية'),
('services','card4','f2','Custom Fabrication','تصنيع مخصص'),
('services','card4','f3','Structural Engineering','هندسة هيكلية'),
('services','card4','f4','Premium Materials','خامات ممتازة'),
('services','card4','f5','Quick Assembly Systems','أنظمة تجميع سريع'),
('services','card4','f6','Maintenance Support','دعم الصيانة'),
('services','card4','p1','Site Assessment & Planning','تقييم الموقع والتخطيط'),
('services','card4','p2','Structural Design','التصميم الهيكلي'),
('services','card4','p3','Material Selection','اختيار المواد'),
('services','card4','p4','Fabrication & QC','التصنيع ومراقبة الجودة'),
('services','card4','p5','Installation & Testing','التركيب والاختبار'),
('services','card4','p6','Handover & Training','التسليم والتدريب'),
-- ADDITIONAL SERVICES
('services','additional','label','Support Services','خدمات الدعم'),
('services','additional','heading','Additional','إضافية'),
('services','additional','heading2','Services','خدمات'),
('services','additional','subtitle','Comprehensive support to ensure every project''s complete success','دعم شامل لضمان نجاح كل مشروع بالكامل'),
('services','additional','s1_title','Branding & Graphics','هوية بصرية وجرافيك'),
('services','additional','s1_desc','Banners, signage, lightboxes, and full visual branding that elevates your presence at any show.','بانرات، لافتات، لايتبوكسات، وهوية بصرية متكاملة ترفع مستوى حضورك في أي معرض.'),
('services','additional','s2_title','Technical Support','دعم تقني'),
('services','additional','s2_desc','24/7 on-site technical support during events and exhibitions — no detail is too small.','دعم تقني ميداني على مدار الساعة أثناء الفعاليات والمعارض — لا تفاصيل صغيرة.'),
('services','additional','s3_title','Logistics Management','إدارة اللوجستيات'),
('services','additional','s3_desc','Complete logistics coordination including shipping, storage, and transportation management.','تنسيق لوجستي متكامل يشمل الشحن والتخزين والنقل.'),
('services','additional','s4_title','Project Management','إدارة المشاريع'),
('services','additional','s4_desc','Dedicated project managers ensuring on-time, on-budget delivery with zero surprises.','مديرو مشاريع متخصصون يضمنون التسليم في الوقت المحدد وبالميزانية المقررة.'),
-- WHY CHOOSE US
('services','why','label','Why Choose Us','لماذا موبي؟'),
('services','why','heading','Why Choose MOPi?','لماذا تختار موبي؟'),
('services','why','w1_title','On-Time Delivery','التسليم في الموعد'),
('services','why','w1_desc','We meet every deadline — no excuses, no exceptions.','نلتزم بكل موعد — بدون أعذار.'),
('services','why','w2_title','Award-Winning Design','تصاميم حائزة على جوائز'),
('services','why','w2_desc','Multiple industry awards for innovation and excellence.','جوائز صناعية متعددة للابتكار والتميز.'),
('services','why','w3_title','Premium Quality','جودة عالية'),
('services','why','w3_desc','Uncompromising quality at every material, finish, and structural detail.','جودة لا تهاون فيها في كل خامة وتشطيبة وتفصيلة هيكلية.'),
('services','why','w4_title','Expert Team','فريق متخصص'),
('services','why','w4_desc','8+ years of specialists in design, production, and live events.','8+ سنوات من المتخصصين في التصميم والإنتاج والفعاليات.'),
('services','why','w5_title','A-to-Z Service','خدمة من أول لآخر'),
('services','why','w5_desc','Concept, logistics, setup, management — all under one roof.','الفكرة، اللوجستيات، التركيب، الإدارة — كل شيء تحت سقف واحد.'),
('services','why','w6_title','8+ Years Experience','8+ سنوات خبرة'),
('services','why','w6_desc','Proven track record delivering 500+ projects across the MENA region.','سجل حافل بتسليم +500 مشروع في منطقة الشرق الأوسط.'),
-- INDUSTRIES
('services','industries','label','Sectors We Serve','القطاعات التي نخدمها'),
('services','industries','heading','Industries We Serve','القطاعات التي نخدمها'),
('services','industries','subtitle','Our expertise spans multiple industries with tailored solutions','خبرتنا تمتد عبر قطاعات متعددة بحلول مخصصة'),
('services','industries','i1','Technology & IT','تكنولوجيا المعلومات'),
('services','industries','i2','Healthcare & Pharma','الصحة والدواء'),
('services','industries','i3','Automotive','السيارات'),
('services','industries','i4','Financial Services','الخدمات المالية'),
('services','industries','i5','Consumer Goods','السلع الاستهلاكية'),
('services','industries','i6','Energy & Utilities','الطاقة والمرافق'),
('services','industries','i7','Education','التعليم'),
('services','industries','i8','Government & Public','الحكومة والقطاع العام'),
-- CTA
('services','cta','label','Let''s Get Started','لنبدأ معاً'),
('services','cta','heading','Ready to Start','مستعد لبدء'),
('services','cta','heading2','Your Project?','مشروعك؟'),
('services','cta','subtitle','Let''s discuss your exhibition needs and create a custom solution that exceeds expectations.','دعنا نناقش احتياجات معرضك ونصنع لك حلاً مخصصاً يفوق التوقعات.'),
('services','cta','cta_primary','Free Consultation','استشارة مجانية')
ON CONFLICT (page,section,field) DO UPDATE
SET value_en = EXCLUDED.value_en, value_ar = EXCLUDED.value_ar;
